@startuml
'https://plantuml.com/class-diagram

class Workout <<Entity>> {
WorkoutPlan! plan
List<TrackedExercise>! exercises;
OffsetDateTime! startTime
OffsetDateTime! endTime
}

class WorkoutPlan <<Entity>> {
String! name
List<ExercisePlanEntry>! exercises
List<DayOfWeek>! weekDays
}

enum TrackingData {
DURATION
DISTANCE
WEIGHT
BODYWEIGHT
REPS
}

class Exercise <<Entity>> {
String! name
String? description
String? link
List<TrackingData>! trackedData

}

class TrackedExercise <<Entity>> {
Exercise! exercise
Duration? duration
Float? distance
Float? weight
Float? bodyweight
int? repetitions
int? partialRepetitions

boolean! toFailure
OffsetDateTime dateTime
int! position
}

class ExercisePlanEntry <<Value Object>> {
Exercise! exercise
int! sets
int position
}

Exercise -- TrackedExercise
Exercise -right- ExercisePlanEntry
ExercisePlanEntry -right- WorkoutPlan
TrackingData -right- Exercise
TrackedExercise -right- Workout
WorkoutPlan -down- Workout

@enduml