CREATE TABLE exercise_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL
);

CREATE TABLE workout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    duration BIGINT NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    average_rest_time DOUBLE PRECISION
);

CREATE TABLE exercise_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    exercise_definition_id BIGINT NOT NULL REFERENCES exercise_definition(id),
    workout_id BIGINT NOT NULL REFERENCES workout(id),
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE set_based_exercise_record (
    id BIGINT NOT NULL PRIMARY KEY REFERENCES exercise_record(id),
    average_rest_time DOUBLE PRECISION,
    weight_kg DOUBLE PRECISION
);

CREATE TABLE exercise_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    exercise_record_id BIGINT NOT NULL REFERENCES set_based_exercise_record(id),
    rest_time BIGINT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    set_duration BIGINT NOT NULL,
    failure BOOLEAN,
    repetitions INTEGER
);

CREATE TABLE distance_exercise_record (
    id BIGINT NOT NULL PRIMARY KEY REFERENCES exercise_record(id),
    distance DOUBLE PRECISION NOT NULL,
    distance_unit VARCHAR(50) NOT NULL,
    duration BIGINT NOT NULL,
    distance_per_unit DOUBLE PRECISION,
    weight_kg DOUBLE PRECISION
);
